[dev]
dev_mode = true

[access]
password_reset_cookie_binding = false

[auth_headers]
enable = true

[database]
pg_host = 'localhost'
pg_user = 'rauthy'
pg_password = '123SuperSafe'

[backchannel_logout]
danger_allow_http = true
danger_allow_insecure = true

[cluster]
node_id = 1
nodes = ["1 localhost:8100 localhost:8200"]
log_statements = true
log_sync = "interval_200"
password_dashboard = "JGFyZ29uMmlkJHY9MTkkbT0zMix0PTIscD0xJE9FbFZURnAwU0V0bFJ6ZFBlSEZDT0EkTklCN0txTy8vanB4WFE5bUdCaVM2SlhraEpwaWVYOFRUNW5qdG9wcXkzQQ=="
secret_raft = "SuperSecureSecret1337"
secret_api = "SuperSecureSecret1337"

[dynamic_clients]
enable = true

[email]
rauthy_admin_email = 'admin@localhost'

[ephemeral_clients]
enable = true
enable_web_id = true
enable_solid_aud = true
allowed_flows = ['authorization_code', 'refresh_token']

[hashing]
argon2_m_cost = 32768
argon2_t_cost = 1
argon2_p_cost = 2
max_hash_threads = 1

[http_client]
danger_unencrypted = true
danger_insecure = true

[logging]
level = 'debug'

[mfa]
admin_force_mfa = false

[pow]
difficulty = 10

[server]
port_http = 8081
port_https = 8444
pub_url = 'localhost:8081'
http_workers = 1
