FROM alpine:3.18.3
#FROM gcr.io/distroless/cc:debug
#FROM gcr.io/distroless/cc

ARG BINARY

USER 10001:10001

WORKDIR /app

COPY --chown=10001:10001 /out/"$BINARY" ./rauthy
RUN mkdir data

COPY --chown=10001:10001 tls/ ./tls/
COPY --chown=10001:10001 rauthy.deploy.cfg ./rauthy.cfg

CMD ["/app/rauthy"]
