#ä This is an optional file. It followes the exact same layout as the config.toml. The only
## allowed values inside here are actual secrets or sensitive information. When you specify
## a value name like `$SECRETS` for any secret in the main config file, it will be read from
## this file instead. For a value like `encryption.keys`, which expects an array, provide an
## array with a single argument called `$SECRETS` instead. All other values are simple strings.
## For further documentation on these values, see their definition in the main config file.

[cluster]
secret_raft = "SuperSecureSecret1337"
secret_api = "SuperSecureSecret1337"
s3_key = "my_key"
s3_secret = "my_secret"
password_dashboard = "JGFyZ29uMmlkJHY9MTkkbT0zMix0PTIscD0xJE9FbFZURnAwU0V0bFJ6ZFBlSEZDT0EkTklCN0txTy8vanB4WFE5bUdCaVM2SlhraEpwaWVYOFRUNW5qdG9wcXkzQQ=="

[database]
pg_user = 'rauthy'
pg_password = '123SuperSafe'

[dynamic_clients]
reg_token = '123SuperSafeToken'

[email]
smtp_username = 'rauthy@localhost'
smtp_password = '123SuperSafe'
xoauth_client_id = ''
xoauth_client_secret = ''

[encryption]
keys = [
    'q6u26onRvXVG4427/M0NFQzhSSldCY01rckJNa1JYZ3g2NUFtSnNOVGdoU0E=',
    'bVCyTsGaggVy5yqQ/UzluN29DZW41M3hTSkx6Y3NtZmRuQkR2TnJxUTYzcjQ=',
]
key_active = 'bVCyTsGaggVy5yqQ'

[events]
matrix_user_id = ''
matrix_access_token = ''
matrix_user_password = ''
slack_webhook = ''

[geolocation]
maxmind_account_id = ''
maxmind_license_key = ''

[user_pictures]
s3_key = ''
s3_secret = ''
