[vault]

# The full address to your vault including scheme and port
#
# default: <empty>
# overwritten by: VAULT_ADDR
addr = ''

# The token that rauthy uses to access the secret
#
# default: <empty>
# overwritten by: VAULT_TOKEN
token = ''

# Secret engine mount point
#
# default: <empty>
# overwritten by: VAULT_MOUNT
mount = ''

# Path within the mount point containing the secret
#
# default: <empty>
# overwritten by: VAULT_PATH
path = ''

# The key (name) of the secret
#
# default: <empty>
# overwritten by: VAULT_CONFIG_KEY
config_key = ''

# KV Version that the secret engine uses.
# Valid values are '1' or '2'.
#
# default: '2'
# overwritten by: VAULT_KV_VERSION
kv_version = ''

# You can provide a root certificate bundle, if you
# are running servers / clients Rauthy needs to connect
# to with self-signed certificates.
# The certificates need to be in PEM format.
#
# overwritten by: HTTP_CUST_ROOT_CA_BUNDLE
#root_ca_bundle = """
#-----BEGIN CERTIFICATE-----
#...
#-----END CERTIFICATE-----
#"""

# If you are testing locally with insecure connections,
# you can set the following var to make it work.
#
# Note: This must be an ENV var and cannot be
# given as a normal TOML value. It only exists here
# for completeness / documentation.
#
#DANGER_VAULT_INSECURE=true
