{{- if .Values.config.enable }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rauthy.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  config.toml: |-
    {{ with .Values.config.bootstrap -}}
    [bootstrap]
      admin_email="{{ $.Values.adminEmail }}"
      password_plain="{{ .password_plain }}"
    {{ end -}}
    
    [cluster]
      node_id_from="k8s"
      node_id=1
      nodes= [
    {{- range $i := (until (.Values.replicaCount | int)) }}
        "{{ add $i  1}} {{ include "rauthy.hostRaftSyncPortsByIndex" (list $ $i) }}",
    {{- end }}
      ]
      secret_raft=
      {{- with .Values.config.cluster.secret_raft -}}
        "{{ . }}"
      {{- else -}}
        "{{ randAlphaNum 48 }}"
      {{- end }}
      secret_api=
      {{- with .Values.config.cluster.secret_api -}}
        "{{ . }}"
      {{- else -}}
        "{{ randAlphaNum 48 }}"
      {{- end }}
    
    [email]
      rauthy_admin_email="{{ .Values.adminEmail }}"
      smtp_url="{{ .Values.config.email.smtp_host }}"
      smtp_port={{ .Values.config.email.smtp_port }}
      danger_insecure={{ .Values.config.email.danger_insecure }}
    
    [encryption]
    {{- with .Values.config.encryption.keys }}
    {{- range . }}
      keys=[
        "{{ . }}",
      ]
      key_active="{{ $.Values.config.encryption.key_active }}"
    {{- end }}
    {{- else }}
    {{- $key_id := ( printf "Auto%s" ( now | date "20060102T150405" ) ) }}
      keys=[
        "{{ $key_id }}/{{ randBytes 32 }}",
      ]
      key_active="{{ $key_id }}"
    {{- end }}
    
    [hashing]
      argon2_m_cost=131072
      argon2_t_cost=4
      argon2_p_cost=8
      max_hash_threads=2
    
    [mfa]
      admin_force_mfa = false
    
    [server]
      port_http={{ .Values.config.server.port_http }}
      port_https={{ .Values.config.server.port_https }}
    {{- if .Values.config.server.port_https }}
      scheme="http_https"
    {{- else }}
      scheme="http"
    {{- end }}
    {{- with index .Values.ingress.hosts }}
      pub_url="{{ (first .).host }}"
    {{- end }}
      proxy_mode=true
      trusted_proxies=[
    {{- range .Values.config.server.trusted_proxies }}
        "{{ . }}",
    {{- end }}
      ]
      swagger_ui_enable={{ .Values.config.server.swagger_enable }}
    
    [[templates]]
      lang="en"
      typ="password_new"
    
    [tls]
      cert_path="tls/cert-chain.pem"
      key_path="tls/key.pem"
    
    [webauthn]
      rp_id="{{ .Values.webauthn.rp_id }}"
      rp_origin="{{ .Values.webauthn.rp_origin }}"
{{- end }}
