{{- if and (not .Values.secrets.existingSecret) .Values.secrets.content -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rauthy.secretsSecretName" . }}
  labels:
    {{- include "rauthy.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.secrets.existingSecretKey }}: |
{{ .Values.secrets.content | indent 4 }}
{{- end }}
