http:
  routers:
    rauthy:
      entrypoints: websecure
      rule: Path(`/whoami`)
      middlewares:
        - add-prefix
        - fwd-auth
      service: whoami

  middlewares:
    add-prefix:
      addPrefix:
        prefix: /auth/v1
    fwd-auth:
      forwardAuth:
        # the id for the properly configured client is `test` in this case
        address: http://localhost:8080/auth/v1/clients/test/forward_auth?redirect_state=302
        trustForwardHeader: true
        authResponseHeaders:
          - x-forwarded-user
          - x-forwarded-user-roles
          - x-forwarded-user-groups
          - x-forwarded-user-email
          - x-forwarded-user-email-verified
          - x-forwarded-user-family-name
          - x-forwarded-user-given-name
          - x-forwarded-user-mfa

  services:
    whoami:
      loadBalancer:
        servers:
          - url: http://localhost:8080
